// ===== 管理员权限 =====

// 图书管理
export const BOOK_CREATE = 'BOOK_CREATE'
export const BOOK_READ = 'BOOK_READ'
export const BOOK_UPDATE = 'BOOK_UPDATE'
export const BOOK_DELETE = 'BOOK_DELETE'
export const BOOK_BATCH_DELETE = 'BOOK_BATCH_DELETE'
export const BOOK_EXPORT = 'BOOK_EXPORT'

// 读者管理
export const READER_CREATE = 'READER_CREATE'
export const READER_READ = 'READER_READ'
export const READER_UPDATE = 'READER_UPDATE'
export const READER_DELETE = 'READER_DELETE'
export const READER_BATCH_DELETE = 'READER_BATCH_DELETE'
export const READER_EXPORT = 'READER_EXPORT'

// 分类管理
export const CATEGORY_CREATE = 'CATEGORY_CREATE'
export const CATEGORY_READ = 'CATEGORY_READ'
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE'
export const CATEGORY_DELETE = 'CATEGORY_DELETE'

// 借阅管理
export const BORROW_CREATE = 'BORROW_CREATE'
export const BORROW_READ = 'BORROW_READ'
export const BORROW_UPDATE = 'BORROW_UPDATE'
export const BORROW_EXPORT = 'BORROW_EXPORT'

// 预约管理
export const RESERVATION_READ = 'RESERVATION_READ'
export const RESERVATION_UPDATE = 'RESERVATION_UPDATE'

// 评价管理
export const REVIEW_READ = 'REVIEW_READ'
export const REVIEW_UPDATE = 'REVIEW_UPDATE'
export const REVIEW_DELETE = 'REVIEW_DELETE'
export const REVIEW_BATCH_DELETE = 'REVIEW_BATCH_DELETE'

// 文件管理
export const FILE_CREATE = 'FILE_CREATE'
export const FILE_READ = 'FILE_READ'
export const FILE_DELETE = 'FILE_DELETE'

// 仪表盘
export const DASHBOARD_READ = 'DASHBOARD_READ'

// 审计日志
export const AUDIT_LOG_READ = 'AUDIT_LOG_READ'

// 管理员申请审批
export const ADMIN_APPLICATION_REVIEW = 'ADMIN_APPLICATION_REVIEW'

// 申诉管理
export const APPEAL_READ = 'APPEAL_READ'
export const APPEAL_REVIEW = 'APPEAL_REVIEW'

// 系统管理
export const ROLE_MANAGE = 'ROLE_MANAGE'
export const PERMISSION_MANAGE = 'PERMISSION_MANAGE'
export const PERMISSION_BATCH_DELETE = 'PERMISSION_BATCH_DELETE'
export const PERMISSION_EXPORT = 'PERMISSION_EXPORT'
export const USER_ROLE_ASSIGN = 'USER_ROLE_ASSIGN'

// ===== 读者权限 =====

// 预约
export const READER_RESERVATION_CREATE = 'READER_RESERVATION_CREATE'
export const READER_RESERVATION_READ = 'READER_RESERVATION_READ'
export const READER_RESERVATION_CANCEL = 'READER_RESERVATION_CANCEL'

// 评价
export const READER_REVIEW_CREATE = 'READER_REVIEW_CREATE'
export const READER_REVIEW_READ = 'READER_REVIEW_READ'
export const READER_REVIEW_UPDATE = 'READER_REVIEW_UPDATE'
export const READER_REVIEW_DELETE = 'READER_REVIEW_DELETE'

// 阅读进度
export const READING_PROGRESS_CREATE = 'READING_PROGRESS_CREATE'
export const READING_PROGRESS_READ = 'READING_PROGRESS_READ'
export const READING_PROGRESS_UPDATE = 'READING_PROGRESS_UPDATE'
export const READING_PROGRESS_DELETE = 'READING_PROGRESS_DELETE'

// 管理员申请
export const ADMIN_APPLICATION_APPLY = 'ADMIN_APPLICATION_APPLY'
export const ADMIN_APPLICATION_STATUS = 'ADMIN_APPLICATION_STATUS'

// 个人中心
export const READER_PROFILE_READ = 'READER_PROFILE_READ'
export const READER_PROFILE_UPDATE = 'READER_PROFILE_UPDATE'

// 图书浏览
export const READER_BOOK_BROWSE = 'READER_BOOK_BROWSE'
export const READER_CATEGORY_BROWSE = 'READER_CATEGORY_BROWSE'

// 借阅记录
export const READER_BORROW_READ = 'READER_BORROW_READ'

// 申诉
export const READER_APPEAL_CREATE = 'READER_APPEAL_CREATE'
export const READER_APPEAL_VIEW = 'READER_APPEAL_VIEW'

// 权限码中文名称映射（用于反馈提示）
export const PERMISSION_LABELS = {
  BOOK_CREATE: '新增图书',
  BOOK_READ: '查看图书',
  BOOK_UPDATE: '编辑图书',
  BOOK_DELETE: '删除图书',
  BOOK_BATCH_DELETE: '批量删除图书',
  BOOK_EXPORT: '导出图书数据',
  READER_CREATE: '新增读者',
  READER_READ: '查看读者',
  READER_UPDATE: '编辑读者',
  READER_DELETE: '删除读者',
  READER_BATCH_DELETE: '批量删除读者',
  READER_EXPORT: '导出读者数据',
  CATEGORY_CREATE: '新增分类',
  CATEGORY_READ: '查看分类',
  CATEGORY_UPDATE: '编辑分类',
  CATEGORY_DELETE: '删除分类',
  BORROW_CREATE: '新增借阅',
  BORROW_READ: '查看借阅',
  BORROW_UPDATE: '操作借阅',
  BORROW_EXPORT: '导出借阅数据',
  RESERVATION_READ: '查看预约',
  RESERVATION_UPDATE: '处理预约',
  REVIEW_READ: '查看评价',
  REVIEW_UPDATE: '审核评价',
  REVIEW_DELETE: '删除评价',
  REVIEW_BATCH_DELETE: '批量删除评价',
  FILE_CREATE: '上传文件',
  FILE_READ: '查看文件',
  FILE_DELETE: '删除文件',
  DASHBOARD_READ: '查看仪表盘',
  AUDIT_LOG_READ: '查看审计日志',
  ADMIN_APPLICATION_REVIEW: '审批管理员申请',
  APPEAL_READ: '查看申诉',
  APPEAL_REVIEW: '处理申诉',
  ROLE_MANAGE: '角色管理',
  PERMISSION_MANAGE: '权限管理',
  PERMISSION_BATCH_DELETE: '批量删除权限',
  PERMISSION_EXPORT: '导出权限清单',
  USER_ROLE_ASSIGN: '用户角色分配',
  READER_RESERVATION_CREATE: '创建预约',
  READER_RESERVATION_READ: '查看我的预约',
  READER_RESERVATION_CANCEL: '取消预约',
  READER_REVIEW_CREATE: '发表评价',
  READER_REVIEW_READ: '查看我的评价',
  READER_REVIEW_UPDATE: '编辑评价',
  READER_REVIEW_DELETE: '删除评价',
  READING_PROGRESS_CREATE: '记录阅读进度',
  READING_PROGRESS_READ: '查看阅读进度',
  READING_PROGRESS_UPDATE: '更新阅读进度',
  READING_PROGRESS_DELETE: '删除阅读记录',
  ADMIN_APPLICATION_APPLY: '申请成为管理员',
  ADMIN_APPLICATION_STATUS: '查看申请状态',
  READER_PROFILE_READ: '查看个人资料',
  READER_PROFILE_UPDATE: '编辑个人资料',
  READER_BOOK_BROWSE: '浏览图书',
  READER_CATEGORY_BROWSE: '浏览分类',
  READER_BORROW_READ: '查看借阅记录',
  READER_APPEAL_CREATE: '提交申诉',
  READER_APPEAL_VIEW: '查看申诉'
}
