package com.kidsbook.common;

public enum Permission {
    // 图书管理（管理员专属）
    BOOK_CREATE, BOOK_READ, BOOK_UPDATE, BOOK_DELETE,
    // 读者管理（管理员专属）
    READER_CREATE, READER_READ, READER_UPDATE, READER_DELETE,
    // 分类管理（管理员专属写操作）
    CATEGORY_CREATE, CATEGORY_READ, CATEGORY_UPDATE, CATEGORY_DELETE,
    // 借阅管理（管理员专属）
    BORROW_CREATE, BORROW_READ, BORROW_UPDATE,
    // 预约管理（管理员审批）
    RESERVATION_READ, RESERVATION_UPDATE,
    // 评论管理（管理员审核）
    REVIEW_READ, REVIEW_UPDATE, REVIEW_DELETE,
    // 文件管理（管理员专属）
    FILE_CREATE, FILE_READ, FILE_DELETE,
    // 仪表盘（管理员专属）
    DASHBOARD_READ,
    // 审计日志（管理员专属）
    AUDIT_LOG_READ,
    // 管理员申请审批（管理员专属）
    ADMIN_APPLICATION_REVIEW,

    // === 读者专属权限 ===
    // 读者个人预约
    READER_RESERVATION_CREATE, READER_RESERVATION_READ, READER_RESERVATION_CANCEL,
    // 读者个人评论
    READER_REVIEW_CREATE, READER_REVIEW_READ, READER_REVIEW_UPDATE, READER_REVIEW_DELETE,
    // 读者阅读进度
    READING_PROGRESS_CREATE, READING_PROGRESS_READ, READING_PROGRESS_UPDATE, READING_PROGRESS_DELETE,
    // 读者申请成为管理员（仅读者可执行）
    ADMIN_APPLICATION_APPLY, ADMIN_APPLICATION_STATUS,
    // 读者个人中心
    READER_PROFILE_READ, READER_PROFILE_UPDATE,
    // 读者浏览图书和分类
    READER_BOOK_BROWSE, READER_CATEGORY_BROWSE,
    // 读者借阅记录查看
    READER_BORROW_READ,
    // 读者申诉
    READER_APPEAL_CREATE,

    // === 系统管理权限 ===
    ROLE_MANAGE, PERMISSION_MANAGE, USER_ROLE_ASSIGN
}
